# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [windows-latest]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1
        
      - name: Setup NuGet.exe for use with actions
        uses: NuGet/setup-nuget@v1.0.5
        
      - name: Restore Nuget packages
        run: nuget restore BronkhorstProParSerialCommunicationTest.sln
        
      - name: Build solution
        run : msbuild BronkhorstProParSerialCommunicationTest.sln
        
      - name: Deploy solution
        run : msbuild BronkhorstProParSerialCommunicationTest.sln /p:DeployOnBuild=true
 
      - name: Upload Artifact
        if: ${{ job.status }}
        uses: actions/create-release@v1
        id: create_release
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
        
      - uses: csexton/release-asset-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pattern: BronkhorstConsole/bin/Published/*
          release-url: ${{ steps.create_release.outputs.upload_url }}

        
